[package]
name = "race-omaha-cash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
race-api.workspace = true
race-proc-macro.workspace = true
borsh.workspace = true
race-poker-base = { path = "../base" }

[dev-dependencies]
race-test.workspace = true
